name: Deploy Vue App to Aliyun ECS

on:
  workflow_run:
    workflows: ['CI']
    types: [completed]
    branches: [master, main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: pnpm build

      # 5. 通过 rsync 上传 dist/ 内容到 ECS
      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: /opt/web/exam/
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}
          remote_port: ${{ secrets.SERVER_PORT}}

      # 刷新阿里云 CDN 目录缓存
      - name: Setup Aliyun CLI
        uses: jerray/setup-aliyun-cli-action@v1.0.2
        with:
          aliyun-cli-version: '3.3.22'
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          region: cn-hangzhou

      - name: Purge Aliyun CDN Cache
        run: | # 执行刷新命令
          aliyun cdn RefreshObjectCaches \
            --ObjectPath "${{ secrets.CDN_REFRESH_URL }}" \
            --ObjectType Directory \
            --region cn-hangzhou
